#!/bin/bash

# Special
hyprctl keyword windowrule "workspace special silent, $TERMINAL"
hyprctl dispatch exec $TERMINAL

# File Manager
hyprctl keyword windowrule "workspace 3 silent, $FILE_MANAGER_GUI"
hyprctl dispatch exec $FILE_MANAGER_GUI

# Terminal
hyprctl keyword windowrule "workspace 5 silent, $TERMINAL"
hyprctl dispatch exec $TERMINAL


# Clean after start
sleep 1
hyprctl keyword windowrule "workspace unset, $TERMINAL"
hyprctl keyword windowrule "workspace unset, $FILE_MANAGER_GUI"
