# yazi-rs/plugins:chmod
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

# boydaihungst/mediainfo
[[mgr.prepend_keymap]]
on = "<F9>"
run = "plugin mediainfo -- toggle-metadata"
desc = "Toggle media preview metadata"

# XYenon/clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ "yank", 'plugin clipboard -- --action=copy' ]

[[mgr.prepend_keymap]]
on  = "<C-p>"
run = [ 'plugin clipboard -- --action=paste' ]

# pirafrank/what-size
[[mgr.prepend_keymap]]
on = [ ".", "s" ]
run  = "plugin what-size"
desc = "Calc size of selection or cwd"

# yazi-rs/plugins:smart-enter
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
