from themes.nord import *

# Themes
BACKGROUND = BACKGROUND_COLOR
FOREGROUND = FOREGROUND_COLOR

GREY = COLOR_01
RED = COLOR_02
GREEN = COLOR_03
YELLOW = COLOR_04
BLUE = COLOR_05
MAGENTA = COLOR_06
CYAN = COLOR_07
WHITHE = COLOR_08

GREY_ALT = COLOR_09
RED_ALT = COLOR_10
GREEN_ALT = COLOR_11
YELLOW_ALT = COLOR_12
BLUE_ALT = COLOR_13
MAGENTA_ALT = COLOR_14
CYAN_ALT = COLOR_15
WHITE_ALT = COLOR_16
